"""Refactor supplies model to support multiple purchases and consumption tracking

Revision ID: 2999a5228b35
Revises: aa3dae34cc27
Create Date: 2026-01-04 21:17:50.068944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2999a5228b35'
down_revision: Union[str, Sequence[str], None] = 'aa3dae34cc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Get connection to check if tables exist
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    # Create new tables only if they don't exist
    if 'supply_consumptions' not in existing_tables:
        op.create_table('supply_consumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('quantity_consumed', sa.Float(), nullable=False),
    sa.Column('quantity_remaining', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
        )

    if 'supply_purchases' not in existing_tables:
        op.create_table('supply_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
        )

    # Migrate existing data from supplies to supply_purchases
    # Each existing supply record becomes a purchase record
    # Only do this if supply_purchases was just created and is empty
    if 'supply_purchases' not in existing_tables:
        supplies = connection.execute(sa.text('SELECT * FROM supplies')).fetchall()

        for supply in supplies:
            connection.execute(
                sa.text(
                    'INSERT INTO supply_purchases (supply_id, purchase_date, quantity, unit, '
                    'unit_price, total_price, notes, created_at, updated_at) '
                    'VALUES (:supply_id, :purchase_date, :quantity, :unit, '
                    ':unit_price, :total_price, :notes, :created_at, :updated_at)'
                ),
                {
                    'supply_id': supply.id,
                    'purchase_date': supply.purchase_date if supply.purchase_date else sa.func.current_date(),
                    'quantity': supply.quantity,
                    'unit': supply.unit,
                    'unit_price': supply.unit_price,
                    'total_price': supply.total_price,
                    'notes': supply.notes,
                    'created_at': supply.created_at,
                    'updated_at': supply.updated_at
                }
            )

    # SQLite doesn't support ALTER COLUMN, skip this
    # op.alter_column('sales', 'customer_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # Use batch mode for SQLite to modify supplies table
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_supply_name', ['supply_name'])
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('quantity')
        batch_op.drop_column('notes')
        batch_op.drop_column('unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('uq_supply_name', type_='unique')

    # SQLite doesn't support ALTER COLUMN, skip this
    # op.alter_column('sales', 'customer_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_table('supply_purchases')
    op.drop_table('supply_consumptions')
    # ### end Alembic commands ###
