"""add_cash_cuts_table

Revision ID: c4b725d8a194
Revises: ceb6bc0026fe
Create Date: 2026-02-22 14:37:49.847172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b725d8a194'
down_revision: Union[str, Sequence[str], None] = 'ceb6bc0026fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_cuts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('sales_count', sa.Integer(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('sales_total', sa.Float(), nullable=True),
    sa.Column('orders_total', sa.Float(), nullable=True),
    sa.Column('expected_total', sa.Float(), nullable=True),
    sa.Column('declared_cash', sa.Float(), nullable=True),
    sa.Column('declared_card', sa.Float(), nullable=True),
    sa.Column('declared_transfer', sa.Float(), nullable=True),
    sa.Column('declared_total', sa.Float(), nullable=True),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_cuts')
    # ### end Alembic commands ###
